name: Check almalinux.org for broken links with lychee

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  # Links can go stale
  schedule:
    - cron: "00 13 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # We pin third-party actions to ensure they're immutable
      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.127.0'
          # extended: true

      - name: Build Site
        run: hugo --minify

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          args: --accept '429' --exclude-path public/blog public/

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5.0.0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue